<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../../../../css/style.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <title>C++</title>
</head>

<body>

  <div class="secondary-color sticky-top">
    <header class="container sticky-top">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">С++</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="../../../../index.html">Главная</a>
              <a class="nav-link" href="../../../lessons.html">Уроки</a>
              <a class="nav-link" href="../../../practicals.html">Практические</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
  </div>

  <main>
    <div class="container-xxl my-md-4 bd-layout">
      <div class="row">
        <div class="col-sm-8 mx-auto">
          <h1>Типы исключений</h1>
          <p>Кроме типа exception в C++ есть еще несколько производных типов исключений, которые могут использоваться
            при различных ситуациях. Основные из них:</p>
          <ul>
            <li><strong>runtime_error</strong>: общий тип исключений, которые возникают во время выполнения</li>
            <li><strong>range_error</strong>: исключение, которое возникает, когда полученный результат превосходит
              допустимый диапазон</li>
            <li><strong>overflow_error</strong>: исключение, которое возникает, если полученный результат превышает
              допустимый диапазон</li>
            <li><strong>underflow_error</strong>: исключение, которое возникает, если полученный в вычислениях результат
              имеет недопустимые отрицательное значение (выход за нижнюю допустимую границу значений)</li>
            <li><strong>logic_error</strong>: исключение, которое возникает при наличии логических ошбок к коде
              программы</li>
            <li><strong>domain_error</strong>: исключение, которое возникает, если для некоторого значения,
              передаваемого в функцию, не определено результата</li>
            <li><strong>invalid_argument</strong>: исключение, которое возникает при передаче в функцию некорректного
              аргумента</li>
            <li><strong>length_error</strong>: исключение, которое возникает при попытке создать объект большего
              размера, чем допустим для данного типа</li>
            <li><strong>out_of_range</strong>: исключение, которое возникает при попытке доступа к элементам вне
              допустимого диапазона</li>
          </ul>
          <img src="./1.png" alt="">
          <p>Большинство этих типов определено в заголовочном файле <strong>stdexcept</strong>, за исключением класса
            <strong>bad_alloc</strong>, который определн в файле <strong>new</strong>, и класса
            <strong>bad_cast</strong>, который определен в файле <strong>type_info</strong>.</p>
          <p>В отличие от классов exception, bad_alloc и bad_cast в конструкторы других типов можно передать строку, то
            есть таким образом можно передать сообщение об ошибке.</p>
          <p>Конструкция try...catch может использовать несколько блоков catch для обработки различных типов исключений.
            При возникновении исключения для его обработки будет выбран тот, который использует тип возникшего
            исключения.</p>
          <p>При использовании нескольких блоков catch вначале помещаются блоки catch, которые обрабатывают более
            частные исключения, а только потом блоки catch с более общими типами исключений:</p>
          <pre>
<code>
#include &lt;iostream>
#include <exception>
#include <stdexcept>
  
double divide(int, int);
  
int main()
{
    int x = 500;
    int y = 0;
    try
    {
        double z = divide(x, y);
        std::cout << z << std::endl;
    }
    catch (std::overflow_error err)
    {
        std::cout << "Overflow_error: " << err.what() << std::endl;
    }
    catch (std::runtime_error err)
    {
        std::cout << "Runtime_error: " << err.what() << std::endl;
    }
    catch (std::exception err)
    {
        std::cout << "Exception!!!"<< std::endl;
    }
    std::cout << "The End..." << std::endl;
    return 0;
}
  
double divide(int a, int b)
{
    if (b == 0)
        throw std::runtime_error("Division by zero!");
    return a / b;
}
</code>
</pre>
          <p>Здесь функция divide, если параметр b равен 0, выбрасывает исключение типа runtime_error. Исключение
            инициализируется сообщением об ошибке "Division by zero!".</p>
          <p>В функции main конструкция try..catch использует три блока catch. Причем последний блок представляет самый
            общий тип исключений exception. Второй блок обрабатывает исключения типа runtime_error, производный от
            exception. А первый блок обрабатывает исключения типа overflow_error, который является производным от
            runtime_error.</p>
          <p>Также все типы исключений имеют метод what(), который возвращает информацию об ошибке. И в данном случае
            программа выдаст следующий результат:</p>
          <pre>
<code>
Runtime_error: Division by zero!
The End...
</code>
</pre>
          <div class="main__pagination">
            <div class="paginator previous"><a href="./lab1.html">
                <img
                  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC0AAAAtCAYAAAA6GuKaAAABRklEQVRoQ+2X4W3CMBCFv0xQRmADugHdpIzQEWCCsgFsUDoBdIOO0BW6AXoSlixInDNtKl91lvIrl/jLy7tnu8Ph6BwyE9B/9ddC6VC6oEDYI+wR9rB5YAY8AQdbeV3VFI04B96Ad2Bdh2Or/m3oR+AISOmNB+gV8HoBlmTNQ79cgPP/2zT0HnjucWOT0PKtGk4p0Teag04JocYbGk1B5wlRyqhmoK8TogQtr+uyjG/g01Kompqc7ksI6zxjdR+F3rh51gothXdjM//g/iTQ4nGndBJRim+BB4OqUu9kqFPJV4X/qzyd5ld6CGYMvJn0SODKaW07F15yOnFqRRT40suKmHO62nvk4O52eUPJ0lwjDvVfnixuoPUxKVnUpC7OiHmyuDqNGxfB+8usG6b7Z5jgyYCeQNTeV4bSoXRBgbBH2OO/2eMMUaUwLofhnv8AAAAASUVORK5CYII=" />
                Лабораторная №1</a></div>
            <div class="paginator next"><a href="./lab3.html">Лабораторная №3<img
                  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC0AAAAtCAYAAAA6GuKaAAABUUlEQVRoQ+2X0U3EMBBE31VAC5RAB0AFQAfQAVRwlAAdQCfQAXRACdABGnT5JN6xFfssraV83Tr3Mpkdb3ZMuHYTMpPQvd5aKp1KryiQ9kh7pD3iHrgG3oDv+JZY5ZaN+AhcATfAVwwnVrU19P6g9CXwEUMqV/WAFoUs8gC8lJHKFb2gF5J74LmMtV7RG1o0UvuuBXwEtHiVKmrQqmQZBS1wNWZVsoyEXhrUThYX+gw4CfrxFtBVWnayuNDy4nmJovL3cLIcE7SeValSzPJjgtbh8xR5Sy60PHoauTFwEbTSDyBrFBVe/teFDvL+lWlg0uyxtgSsh7PmkpHQn4DGV3sCHAX9fgCe5kR8Deb3v7bqrXQ4IdYaoRe0nRCjoasSYiS00qEqIUZBT/k17hxEVu2WjWiBOMUJ7ajVUptKt6jn7E2lHbVaalPpFvWcvVMq/QsQrjouZKOwvQAAAABJRU5ErkJggg==" /></a>
            </div>
          </div>
        </div>

      </div>
    </div>
  </main>

  <div class="secondary-color">
    <footer>
      <p class="footer_p">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris elementum sed ante a suscipit.
        Mauris tempor
        suscipit justo vel lacinia. Curabitur hendrerit lobortis ligula nec.</p>
    </footer>
  </div>

  <!-- scripts -->
  <script src="./js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous">
  </script>
</body>

</html>